apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nmz5uz5kj-nodejs 
  janus-idp.io/tekton: nmz5uz5kj-nodejs
  backstage.io/kubernetes-id: nmz5uz5kj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nmz5uz5kj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml