apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nmz5uz5kj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nmz5uz5kj-nodejs 
  name: nmz5uz5kj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nmz5uz5kj-nodejs 
